### ISSUE TITLE
pusher.connection.socket_id is undefined

### ISSUE THREAD

**Issue by padraigoleary** [dongido001/flask_chatbot#2]
Hey. 

I am getting the following error - 

`pusher.connection.socket_id is undefined `

resulting in 
`werkzeug.exceptions.HTTPException.wrap.<locals>.newcls: 400 Bad Request: KeyError: 'socketId'
`

**Comment by dongido001** [comment]
Hi @padraigoleary 

Did you later fix the issue?

Hope you updated your Pusher keys here: https://github.com/dongido001/flask_chatbot/blob/38bc78da8cd075c97976ab41e953e28e9a94708a/static/custom.js#L2-L7

**Comment by padraigoleary** [comment]
Yes, resolved. Thank you.

**Comment by uttamraj9** [comment]
Hi Padraigoleary,

I am facing the same error:
werkzeug.exceptions.HTTPException.wrap.<locals>.newcls: 400 Bad Request: KeyError: 'socketId'

my code is :
  const pusher = new Pusher('***********', {
      cluster: 'ap2',
      encrypted: true
  });
  });
  function submit_message(message) {
    $.post( "/send_message", {
      message: message, 
      socketId: pusher.connection.socket_id
    }, handle_response);

**Comment by dongido001** [comment]
@uttamraj9, I just pushed a fix for the issue.

Please, pull and try to see if it fixes your error and let me know.

**Comment by uttamraj9** [comment]
Hi Onwuka Gideon , I am not getting that error now.
But I am not able to get movie details from chat windows.

<img width="706" alt="Screen Shot 2019-04-17 at 10 57 05 AM" src="https://user-images.githubusercontent.com/7234899/56267361-9e48aa00-60ff-11e9-9803-5df6651bede7.png">

the response from the server is :
127.0.0.1 - - [17/Apr/2019 10:51:35] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2019 10:51:39] "POST /send_message HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2019 10:52:04] "POST /send_message HTTP/1.1" 200 -

**Comment by dongido001** [comment]
Did you add the app URL as a fulfillment to dialogflow? - https://pusher.com/tutorials/chatbot-flask-dialogflow#setting-up-a-webhook

**Comment by uttamraj9** [comment]
Yes, 
<img width="985" alt="Screen Shot 2019-04-17 at 11 15 32 AM" src="https://user-images.githubusercontent.com/7234899/56268413-55debb80-6102-11e9-98f0-75c409968801.png">

<img width="565" alt="Screen Shot 2019-04-17 at 11 17 36 AM" src="https://user-images.githubusercontent.com/7234899/56268459-7444b700-6102-11e9-9d09-8dba4d591d31.png">

**Comment by dongido001** [comment]
Ok, so you have Ngrok running? can you post the response that was sent to Ngrok. 

You can access your Ngrok from localhost:4040

**Comment by uttamraj9** [comment]
I am not getting any response:
<img width="786" alt="Screen Shot 2019-04-17 at 11 22 42 AM" src="https://user-images.githubusercontent.com/7234899/56268749-31371380-6103-11e9-903a-31ca22a51c4e.png">

**Comment by uttamraj9** [comment]
<img width="1274" alt="Screen Shot 2019-04-17 at 11 35 17 AM" src="https://user-images.githubusercontent.com/7234899/56269549-efa76800-6104-11e9-967e-b447add67380.png">

HTTP/1.0 200 OK
Content-Type: application/json
Content-Length: 20
Server: Werkzeug/0.15.2 Python/3.6.8
Date: Wed, 17 Apr 2019 07:32:26 GMT

{
  "message": ""
}

**Comment by dongido001** [comment]
> Yes,
> <img alt="Screen Shot 2019-04-17 at 11 15 32 AM" width="985" src="https://user-images.githubusercontent.com/7234899/56268413-55debb80-6102-11e9-98f0-75c409968801.png">
> 
> <img alt="Screen Shot 2019-04-17 at 11 17 36 AM" width="565" src="https://user-images.githubusercontent.com/7234899/56268459-7444b700-6102-11e9-9d09-8dba4d591d31.png">

The webhook URL should look like this `*******.ngrok.io/get_movie_detail`

Seems you are missing the `get_movie_detail` part in the URL

**Comment by uttamraj9** [comment]
As mentioned I have uploaded my fulfillment URL, But Still i am getting same issue
<img width="993" alt="Screen Shot 2019-04-17 at 12 01 25 PM" src="https://user-images.githubusercontent.com/7234899/56271168-dc969700-6108-11e9-947a-4130e34baac2.png">

For normal request I am getting the response:
<img width="993" alt="Screen Shot 2019-04-17 at 12 05 27 PM" src="https://user-images.githubusercontent.com/7234899/56271280-2c755e00-6109-11e9-9270-3d2080583bd9.png">

But for movie I am not getting any response 
<img width="988" alt="Screen Shot 2019-04-17 at 12 05 38 PM" src="https://user-images.githubusercontent.com/7234899/56271297-3ac37a00-6109-11e9-8623-42b9b11edf9e.png">

**Comment by dongido001** [comment]
I'm wondering now, I see the request is coming in but as a GET request instead of POST 0 (405 METHOD NOT ALLOWED).

Are you available for TeamView so I can take a look?

**Comment by uttamraj9** [comment]
Sure..
 I will email you my teamviewer id,
Please give me your mail ID

**Comment by dongido001** [comment]
Closing this since there is now a permanent fix for this issue.

**Comment by uttamraj9** [comment]
Thanks for the Fix.. Much Appreciated 👍
