### ISSUE TITLE
NGROK Too Many Connections

### ISSUE THREAD

**Issue by padraigoleary** [dongido001/flask_chatbot#3]
Following the ReadMe as described. Getting a variation of the following every time - 

`Too many connections! The tunnel session 'xxx' has violated the rate-limit policy of 20 connections per minute by initiating 44 connections in the last 60 seconds. Please decrease your inbound connection volume or upgrade to a paid plan for additional capacity.

The error encountered was: ERR_NGROK_702
`
Were you using a paid version of NGROK?

**Comment by dongido001** [comment]
Nope. I used a free version and didn't make that much request.

I'm wondering what's making that much request though.

You might want to host the app online instead (maybe [heroku](https://www.heroku.com/) ) if the request you are making is much.

**Comment by dongido001** [comment]
I'm closing this for now since it's not an issue with the project but Ngrok. 
Feel free to re-open the issue, if you feel otherwise
