### ISSUE TITLE
Doesn't work :(

### ISSUE THREAD

**Issue by vj68** [dongido001/flask_chatbot#6]
Followed the exact same path... isn't working.

The frustrating part is that no error is shown.

Can you list any possibilities why is it not working.

I have obtained all the keys correctly.

**Comment by dongido001** [comment]
No error on your terminal also?

Do you have your code somewhere that I can take a look?

**Comment by vj68** [comment]
Ok first I wrote the code myself. It didn't work.
Then I cloned your repository, it still didn't work. (I added my keys).
I also change the webhook whenever I restart ngrok.
I mean the server is running, I am getting the web page. But the bot isn't responding.
One doubt,while defining the keys, do I put the values in double quotes or not?
I mean should it be 
PUSHER_APP_ID=app_id (OR)
PUSHER_APP_ID="app_id"     ?

**Comment by himelys** [comment]
Hi, I followed your instruction and found one error in line 66 of index.py.
I need to comment out this line to make the program working. socketID is not needed.

**Comment by dongido001** [comment]
@himelys  Thanks for looking into this.

Yeah, socketID is not used and is not required. 

@rajurajvijay619  I am closing this, since there is a solution, please feel free to open the issue with a clear description if you feel otherwise.

Thanks
